name: Build MacOS client
run-name: Build MacOS client
on:
  workflow_dispatch:

jobs:
    build:
        runs-on: macos-latest
        steps:
        - name: Check out the repo
          uses: actions/checkout@v4
          with:
            submodules: true
        - name: Install dependencies
          run: |
            brew install qt5
        - name: Build
          env:
            QT_DIR: "/opt/homebrew/opt/qt@5"
            Qt5_DIR: "/opt/homebrew/opt/qt@5/lib/cmake/Qt5"
          run: |
             cp examples/CMakePresets.json .
             cmake .
             make -j 2
             /opt/homebrew/opt/qt@5/bin/macdeployqt client.app
             sh patch-paths.sh
             zip client.zip -r client.app
    
        - name: Archive production artifacts
          uses: actions/upload-artifact@v4
          with:
            path: client.zip
            name: client.zip