name: Build MacOS client
run-name: Build MacOS client
on:
  workflow_dispatch:

jobs:
    build:
        runs-on: macos-latest
        steps:
        - name: Check out the repo
          uses: actions/checkout@v4
          with:
            submodules: true
        - name: Install dependencies
          run: |
            brew install qt5
        - name: Build
          env:
            Qt5_DIR: "/opt/homebrew/opt/qt@5/lib/cmake/Qt5"
          run: |
             cp examples/CMakePresets.json .
             echo "Qt cmake: $Qt5_DIR"
             ls /opt/homebrew/opt/qt@5/lib/cmake/Qt5/Qt5Config.cmake
             cmake .
    
        - name: Archive production artifacts
          uses: actions/upload-artifact@v4
          with:
            path: client-0.4.1